# Generated by Django 4.2.4 on 2023-08-27 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='curriculos/')),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
