# Generated by Django 4.2.4 on 2023-08-27 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('josefilhodev', '0005_projeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='descricao',
        ),
    ]
