# Generated by Django 4.2.4 on 2023-08-27 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('josefilhodev', '0007_delete_curriculo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificado',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='educacao',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='experiencia',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='certificado',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='educacao',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projeto',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
