# Generated by Django 4.2.4 on 2023-08-27 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('josefilhodev', '0008_alter_certificado_options_alter_educacao_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificado',
            options={'ordering': ['order'], 'verbose_name_plural': 'Certificados'},
        ),
        migrations.AlterModelOptions(
            name='educacao',
            options={'ordering': ['order'], 'verbose_name_plural': 'Educações'},
        ),
        migrations.AlterModelOptions(
            name='experiencia',
            options={'ordering': ['order'], 'verbose_name_plural': 'Experiências'},
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['order'], 'verbose_name_plural': 'Projetos'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order'], 'verbose_name_plural': 'Skills'},
        ),
    ]
