# Generated by Django 4.2.4 on 2023-08-27 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('josefilhodev', '0009_alter_certificado_options_alter_educacao_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educacao',
            options={'ordering': ['order'], 'verbose_name_plural': 'Educação'},
        ),
    ]
