# Generated by Django 4.2.4 on 2023-09-06 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('josefilhodev', '0010_alter_educacao_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificado',
            options={'ordering': ['order'], 'verbose_name_plural': '2 - Certificados'},
        ),
        migrations.AlterModelOptions(
            name='educacao',
            options={'ordering': ['order'], 'verbose_name_plural': '3 - Educação'},
        ),
        migrations.AlterModelOptions(
            name='experiencia',
            options={'ordering': ['order'], 'verbose_name_plural': '4 - Experiências'},
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['order'], 'verbose_name_plural': '5 - Projetos'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['order'], 'verbose_name_plural': '1 - Skills'},
        ),
    ]
